### ISSUE TITLE
Add default CJK fonts from system

### ISSUE THREAD

**Issue by hanaral** [elementary/flatpak-platform#12]
## What Happened
Not sure if this is an issue, but on the 6 daily flatpak apps use a terrible sans serif font for Japanese, and I assume for other languages that use the Chinese alphabet or Korean

## Expected Behavior
The default CJK font that elementary uses should be in place

## Steps to Reproduce
Set language to a language with a CJK font and open a flatpak app

**Comment by ryonakano** [comment]
Hi, can I ask you two things:

- would you tell me in which flatpaked app you're facing the issue so that we can reproduce this?
- would you attach screenshots of the issue?

**Comment by hanaral** [comment]
ＧＴＫやＱｔのアプリはシステムのフォントの代わりに変な文字を使っています
Seems to be the same for all apps. The elementary stylesheet flatpak from flathub seems to make no difference since it's for GTK 3.22 (Neither does the base app - though afaik that wouldn't anyway)
![Screenshot from 2020-12-02 10-55-43](https://user-images.githubusercontent.com/58219504/100878480-28df4800-34a2-11eb-82b3-f4cfc1963e05.png)
![Screenshot from 2020-12-02 13-36-06](https://user-images.githubusercontent.com/58219504/100879804-cbe49180-34a3-11eb-82bc-6da536e1a2f7.png)

**Comment by ryonakano** [comment]
Hmm it is shown correctly on my side:

![Screenshot from 2020-12-03 08-09-37](https://user-images.githubusercontent.com/26003928/100942878-778eef80-353f-11eb-995e-e97278e66be5.png)

Try `sudo apt install -y fonts-noto-cjk-extra` in your terminal. I assume CJK fonts should be installed while installation though.

**Comment by hanaral** [comment]
> Hmm it is shown correctly on my side:
> 
> ![Screenshot from 2020-12-03 08-09-37](https://user-images.githubusercontent.com/26003928/100942878-778eef80-353f-11eb-995e-e97278e66be5.png)

How odd.
 If you don't mind, could you paste the locales you have installed from flathub?

> Try `sudo apt install -y fonts-noto-cjk-extra` in your terminal. I assume CJK fonts should be installed while installation though.

fonts-noto-cjk-extraはもう有ります。それなのに正しいフォントを使っていない

I'm thinking that it's most likely a flatpak thing, since the fonts are all the default install from the Odin image as you said.

**Comment by ryonakano** [comment]
Here is my installed locales and packages:

```bash
ryo@ryo-pc:~/Projects/Tmp$ flatpak list --all
Name                                              Application ID                                   Version           Branch           Installation
Transmission                                      com.transmissionbt.Transmission                  3.00              stable           user
Locale                                            com.transmissionbt.Transmission.Locale                             stable           user
default                                           org.freedesktop.Platform.GL.default                                19.08            user
default                                           org.freedesktop.Platform.GL.default                                20.08            system
openh264                                          org.freedesktop.Platform.openh264                2.1.0             2.0              system
openh264                                          org.freedesktop.Platform.openh264                2.1.0             2.0              user
GNOME Web                                         org.gnome.Epiphany                               3.38.0            stable           system
Locale                                            org.gnome.Epiphany.Locale                                          stable           system
GNOME Application Platform version 3.36           org.gnome.Platform                                                 3.36             user
GNOME Application Platform version 3.38           org.gnome.Platform                                                 3.38             system
Locale                                            org.gnome.Platform.Locale                                          3.36             user
Locale                                            org.gnome.Platform.Locale                                          3.38             system
```

**Comment by hanaral** [comment]
あぁ、問題が私の変体仮名と古い文字ために使っているフォントでした。
Remving the BabelstoneHan font I used solved the issue, I'm probably going to have to use a tool to give it less priority than noto-cjk.

**Comment by ryonakano** [comment]
原因が分かってよかったです！☺️
