### ISSUE TITLE
Confused as to how to compile

### ISSUE THREAD

**Issue by hanaral** [elementary/flatpak-platform#13]
## What Happened

I've tried a couple of times to compile this via meson and ninja, but my drives always run out of space due to what I presume is all the SDKs being installed. I'm not sure if I'm doing something wrong, but this seems pretty unreasonable since it eats up tens of gigabytes.
## Platform Information

elementary OS 6 Daily

**Comment by Marukesu** [comment]
To build the SDK, flatpak-builder needs some others flatpaks. That's the installed size of them from `flatpak info`:
- org.gnome.Sdk: 1,9 GB
- org.gnome.Sdk.Debug: 4,8 GB
- org.gnome.Sdk.Docs:  255,7 MB
- org.gnome.Platform: 948,8 MB

The elementary SDK and Platform are: 
- io.elementary.Sdk: 2,2 GB
- io.elementary.Platform: 997,8 MB

**Comment by hanaral** [comment]
Cheers, but it gives me a compiling error about halfway saying that the org.gnome.Locale is only partially installed. I've tried force reinstalling the package and it still gave the same error, is there a wa to install it fully?

**Comment by Marukesu** [comment]
From [flatpak/flatpak#1059](https://github.com/flatpak/flatpak/issues/1059#issuecomment-333758548):
`flatpak update --user --subpath= org.gnome.Sdk.Locale`
You probably want to add '--user' to command array in meson.build too.

**Comment by hanaral** [comment]
Thanks again, it compiled and installed. However, I cannot manage to get the stylesheet to work.

**Comment by Marukesu** [comment]
Elementary apps are using the Gnome Runtime for now since there wasn't a elementary repo, to use the elementary runtime you need to use `--runtime=io.elementary.Platform//0.1.0` or, if the app is code `--runtime=io.elementary.Sdk//0.1.0`

However, I can't say that every app (in flathub) will work this way because it's override on runtime, and they can be built with other versions of library. (epiphany won't work, for example)

**Comment by hanaral** [comment]
Closing this since it's not really an issue; but could someone add to the README that it may be beneficial to someone's sanity to remove .Debug deps when compiling?
@Marukesu
