### ISSUE TITLE
elementary Sdk should allow developers to have changable app icons

### ISSUE THREAD

**Issue by hanaral** [elementary/flatpak-platform#15]
## Problem

I personally do not care too much about theming - but I know that being able to bundle apps with alternative icons on macOS and iOS is a pretty great feature. Ignoring the theming community around the freedesktop, there is yet to be anyone to provide a solution to people wanting to have such things in an official manner

## Proposal

As a developer you should be able to bundle other official icons, albeit with heavy restrictions on how different they can be. Fondo already has great seasonal icons that the developer changes from time to time. This would likely also remedy the itch people have sometimes to change something, since sandboxed apps are virtually impossible to theme without external .desktop files.

## Prior Art

| | |
| ---------- | ---------- |
Twitteriffic iOS | ![photo_2021-03-03_21-10-01](https://user-images.githubusercontent.com/58219504/109872825-dbbb6f80-7c64-11eb-8540-d4c9d73452f6.jpg) |
Twitteriffic iOS | ![photo_2021-03-03_21-10-09](https://user-images.githubusercontent.com/58219504/109872828-dc540600-7c64-11eb-981a-72a30e86873e.jpg) |

**Comment by Marukesu** [comment]
There's no way to a flatpak app edit its own .desktop file from the sandbox. It would be necessary write a portal to do that.

**Comment by hanaral** [comment]
Ah that sucks - I was thinking maybe elementary could do something on its own end for it rather than messing with the sandbox defaults (iOS seems to do it this way)

**Comment by danrabbit** [comment]
Closing as "Out of scope" for the flatpak platform since this would require a new portal
