### ISSUE TITLE
Include GL extension point

### ISSUE THREAD

**Issue by danrabbit** [elementary/flatpak-platform#19]
Our latest build of Epiphany against the elementary runtime fails on execute with the following:

```
bwrap: Can't mkdir /usr/lib/x86_64-linux-gnu/GL: Read-only file system
```

According to @alatiera:
> something to keep in mind is that the gnome runtime inherits some extension points from flathub, like the .GL  or the .ffmpeg-full ones, which you will need to mirror to your repo in order to be self-contained

**Comment by alatiera** [comment]
List of said extensions can be found here:

https://github.com/elementary/flatpak-platform/blob/4e9994055ff71e64fe40bc2627a19f35f4382c39/io.elementary.Sdk.json.in#L11-L18

**Comment by hanaral** [comment]
Just to add to the list:
```
han@elementary-os:~$ flatpak run io.elementary.music 
bwrap: Can't mkdir /usr/lib/x86_64-linux-gnu/GL: Read-only file system

han@elementary-os:~$ flatpak run io.elementary.calculator 
bwrap: Can't mkdir /usr/lib/x86_64-linux-gnu/GL: Read-only file system

han@elementary-os:~$ flatpak run io.elementary.videos 
bwrap: Can't mkdir /usr/lib/x86_64-linux-gnu/GL: Read-only file system

han@elementary-os:~$ flatpak run io.elementary.calendar 
bwrap: Can't mkdir /usr/lib/x86_64-linux-gnu/GL: Read-only file system
```

**Comment by alatiera** [comment]
@btkostner I haven't built this to confirm yet, but I think this issue might be caused by this line, making it so the inherited extensions are ignored.

https://github.com/elementary/flatpak-platform/blob/main/io.elementary.Sdk.json#L10
