### ISSUE TITLE
Include Gtk3 default settings from elementary os

### ISSUE THREAD

**Issue by tintou** [elementary/flatpak-platform#28]
The file [settings.ini](https://github.com/elementary/default-settings/blob/master/gtk/settings.ini) can be installed in either `/usr/share/gtk-3.0/` or `/etc/gtk-3.0/

**Comment by cassidyjames** [comment]
@tintou is there a strong reason to use one over the other?

**Comment by danrabbit** [comment]
`etc` would be more proper wouldn't it? Since `share` I think is supposed to more be resources the program needs to run and `etc` is supposed to be where system configuration is stored

**Comment by tintou** [comment]
No strong reason to use one or the other, share is used before etc if it does exists but they both work the same https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/gtk/gtksettings.c#L345
