### ISSUE TITLE
Add org.freedesktop.Platform.GL on elementary remote   

### ISSUE THREAD

**Issue by alex285** [elementary/flatpak-platform#32]
I'm not sure this bug actually belongs here, but just to track the issue somewhere

## What Happened
org.gnome.Epiphany from elementary Flatpak remote fails to run webprocess

## Steps to Reproduce
1. add elementary remote `flatpak remote-add elementary https://flatpak.elementary.io/elementary.flatpakrepo`
2. install WebApp `flatpak install elementary org.gnome.Epiphany`
3. run Epiphany `flatpak run org.gnome.Epiphany`

**Results:** Epiphany will start normally but when we try to open a web page even with `hardware-acceleration-policy` to "never", the tab will crash with `Cannot create EGL context: invalid display (last error: EGL_SUCCESS)`

**Solution:** We can add Flathub remote and install ` org.freedesktop.Platform.GL.default //20.08`

I assume the same same applies for NVIDIA Flatpak drivers etc

## Platform Information
elementary-6 pre-release

**Comment by btkostner** [comment]
So, the actual repo for that stuff is here https://gitlab.com/freedesktop-sdk/freedesktop-sdk. My idea is to just create a cron schedule for this repo that clones _their_ repo and runs the build script.

Question being what versions do we need pulled over? Just 20.08 or?

**Comment by alatiera** [comment]
I'd recommend to clone the objects from flathub instead. No need to rebuild and and you won't have to update the tag you need to build manually each time that way.

**Comment by btkostner** [comment]
@alatiera That's a fair point. Do you know the commands needed for that?

**Comment by cassidyjames** [comment]
This makes Web next to useless in the beta, so should be addressed ASAP. As @alex285 mentioned, a workaround for users for now is to install the GL extension from Flathub:

```sh
flatpak remote-add --system --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
```
and then install the extension:

```
flatpak install -y flathub org.freedesktop.Platform.GL.default//20.08
```

**Comment by alatiera** [comment]
So this might end up a bit trickier than I hoped for. Disclaimer I haven't tried either of the following and it might end up easier in the end to rebuild the extensions.

So there are 2 `ostree pull/pull-local` commands but a. they differ depending if the repository is available in a local repo or not, which is a bit weird given that we don't want to have to pull everything before.

And b. ideally we'd want something like `flatpak build-commit-from --untrusted` to import the object instead so it will also manage signing the ref etc.

There are [some docs](https://ostreedev.github.io/ostree/buildsystem-and-repos/#migrating-content-between-repositories/) which you could take a look at, but the usecase they showcase is different in nature.

**Comment by btkostner** [comment]
@alatiera Thank you for the guidance on this! :confetti_ball:

**Comment by btkostner** [comment]
Alright, so the branch seems to be copied into the repo, gpg signing is working correctly. The size is pretty big, so I am assuming it's correct. But now we are getting this issue with old and new beta installs:

```
[btkostner:~/tmp/flathub] 12s % flatpak install appcenter org.freedesktop.Platform.GL.default
Looking for matches…


        ID                                             Branch            Op            Remote              Download
 1. [✗] org.freedesktop.Platform.GL.default            20.08             i             appcenter           1.0 kB / 489.3 MB

Error: Commit metadata for runtime/org.freedesktop.Platform.GL.default/x86_64/20.08 not matching expected metadata
error: Failed to install org.freedesktop.Platform.GL.default: Commit metadata for runtime/org.freedesktop.Platform.GL.default/x86_64/20.08 not matching expected metadata
```

Current script we use for mirroring: https://github.com/elementary/flatpak-platform/blob/main/.github/workflows/mirror.yml

Looking it up it suggests `flatpak repair`, but this seems to be a mirror or repo problem, not on the user side of things.

Anyone here have thoughts?

**Comment by barthalion** [comment]
IMHO there are only two correct solutions. The first one is to ask FreeDesktop SDK team to upload GL extensions to your repository with flat-manager.

The other, one that is somewhat proved to work already for Fedora, is to enable Flathub by default but configure a filter to deny all refs except org.freedesktop.Platform extensions. Filter file format is described in flatpak-remote-add man page.

**Comment by cassidyjames** [comment]
@barthalion alright, we've done the latter here: https://github.com/elementary/os/pull/480. We can always consider something else in the future, but this gets us rolling.

**Comment by cassidyjames** [comment]
So while the extension is made available, it's not pre-installed. Opening an issue on the OS repo for that: https://github.com/elementary/os/issues/492

For anyone else on a recent daily build, this should resolve it:

```
flatpak install --system freedesktop org.freedesktop.Platform.GL.default//20.08
```
