### ISSUE TITLE
Non-native gtk styled apps like Firefox don't use native theme

### ISSUE THREAD

**Issue by hanaral** [elementary/flatpak-platform#44]
## What Happened

Installing the firefox flatpak results in the browser only getting out-of-plaice Adwaita styles, even when overridden to launch with io.elementary.Platform//daily

## Expected Behavior

Firefox flatpak launches in native style like non-sandboxed version

## Steps to Reproduce

1. Install Firefox from Flathub
2. Run with io.elementary.Platform//daily

## Platform Information

elementary OS 6 Beta 1

**Comment by alatiera** [comment]
I this is the expected behavior. Unless we allow flatpak to force override that, which frequently break apps, there isn't much that can be done here.
