### ISSUE TITLE
`flatpak history` does not work

### ISSUE THREAD

**Issue by loaden** [elementary/flatpak-platform#67]
## What Happened
I am try to run 'flatpak history' on terminal, but got this error reports.

> error: appstream2/x86_64 is not application or runtime

## Expected Behavior
It's should show some history about flatpak install or remove stuff.

## Steps to Reproduce
every time.

## Platform Information
elementary OS 6, the latest version

**Comment by cassidyjames** [comment]
It looks like this is an upstream issue that's been addressed upstream but not released yet: https://github.com/flatpak/flatpak/pull/4180

**Comment by repsorp** [comment]
https://github.com/flatpak/flatpak/pull/4180 6 months old ?!
any other way to access history ?
