### ISSUE TITLE
GTK settings in distributions like Feren OS is set to an invalid value

### ISSUE THREAD

**Issue by dominichayesferen** [elementary/flatpak-platform#72]
I'm not sure if this is entirely related to #1 and #28 and the likes, but just in case it's not known it's causing actual issues in non-elementary-OS scenarios, I thought I'd make this extra issue in case. Feel free to close it if it's indeed a duplicate of any existing issues.

## What Happened
Basically elementary OS's applications in the Flatpak format are horribly visually broken in certain, if not all, non-elementary OS environments. A quick DEBUG mode variable shows that the Flatpaks are set to use... nothing (I'm suspecting they're using, in my case, 'feren' and 'Inspire' (the Feren OS theme combo), but since they don't exist inside the Flatpak they're effectively nothing values in the GTK+ debugger).

This is troublesome especially as:
- Applications requiring elementary OS's stylesheet are either somewhat broken or teetering towards complete unusability
- Dark mode applications don't get their dark theme applied

Camera (bug in effect):
![image](https://user-images.githubusercontent.com/11057934/134720427-ecd98033-0a2a-4a79-9bfc-478f8de2343d.png)

Camera (after changing values):
![image](https://user-images.githubusercontent.com/11057934/134720513-3268cc97-d79c-4757-8685-ad17a748da1e.png)

Fondo (bug in effect, also notice that dark mode doesn't work in this buggy state):
![image](https://user-images.githubusercontent.com/11057934/134720627-b43e6fac-9aef-4afc-99b6-ba96935427cc.png)

Fondo (after changing values, dark mode now works):
![image](https://user-images.githubusercontent.com/11057934/134720738-04e00c49-4bc4-4b8a-928b-fc2d829c2d3f.png)

Calendar (bug in effect):
![image](https://user-images.githubusercontent.com/11057934/134720829-05ad3e29-f417-4956-b2b1-8bff01e505d5.png)

Calendar (after changing values):
![image](https://user-images.githubusercontent.com/11057934/134720916-37d85484-ba03-44ea-ad76-1e7aac31dc44.png)

Dippi is the only case I know of of automatic theme setting:
![image](https://user-images.githubusercontent.com/11057934/134721025-2b0667d2-d6f4-4df3-b59c-6f59fc51e0b0.png)

...and finally, while it isn't in AppCenter currently, I'll just demonstrate the potential unusability this bug could, theoretically, cause using Byte (**forced Adwaita values**, to illustrate a point):
![image](https://user-images.githubusercontent.com/11057934/134721522-c78b78a9-0bba-40ff-a69d-3e56dc164d8f.png)

## Expected Behavior
At the very least, the fallback should be io.elementary.stylesheet.blueberry with elementary icon set

## Steps to Reproduce

1. Add the AppCenter repository to a distribution like Feren OS (is easy enough, just follow Linux Mint's instructions)
2. Install io.elementary.camera or any other package from AppCenter that's built around elementary OS's theme
3. Open the newly installed application

## Platform Information

The latest version of Feren OS is in use for this issue report, however I'd suspect this same issue would occur elsewhere, if not just in all KDE Plasma distributions.

**Comment by alatiera** [comment]
> I'm suspecting they're using, in my case, 'feren' and 'Inspire' (the Feren OS theme combo), but since they don't exist inside the Flatpak they're effectively nothing values in the GTK+ debugger).

That's exactly what's happening, the portal is exposing the string of the host style which is not available inside the sandbox.

I don't think running elementary apps on non-elementary OS is a "supported" usecase as of now. In order to fix this there needs to be a guarantee that the application will be using the correct stylesheet.

Dippi for example explicitly sets the style and icon-theme to elementary. another option would be to have `libgranite` do it instead to avoid apps having to "opt-in" the non-broken mode, this is what will be happening in `libadwaita` as well. Or what https://github.com/elementary/flatpak-platform/pull/30 is doing and patch GTK's default itself.

**Comment by dominichayesferen** [comment]
I think the best port of call WOULD be to have LibGranite do it instead, since it's the <b>elementary OS</b> equivalent of LibAdwaita, technically, and there's no way I'd think in normal usage for there to be other theme choices anyway besides io.elementary.stylesheet.idk or Adwaita.

Obviously you'd still need to support your in-house accent variations, but I'm sure that'd be easy enough to do.

**Comment by dominichayesferen** [comment]
Possibly related: #30

**Comment by tintou** [comment]
This is because of https://github.com/flatpak/flatpak/issues/4873

**Comment by Marukesu** [comment]
> This is because of [flatpak/flatpak#4873](https://github.com/flatpak/flatpak/issues/4873)

i don't think so, the issue here is with apps using the elementary runtime. they have the elementary stylesheet in the sandbox already.

i believe the best solution is go the libadwaita route and have it hardcoded as part of the granite library. #30 has some limitations (won't work for icon themes, fonts, and won't respect the dark theme application preference).

**Comment by dominichayesferen** [comment]
> > This is because of [flatpak/flatpak#4873](https://github.com/flatpak/flatpak/issues/4873)
> 
> i don't think so, the issue here is with apps using the elementary runtime. they have the elementary stylesheet in the sandbox already.
> 
> i believe the best solution is go the libadwaita route and have it hardcoded as part of the granite library. #30 has some limitations (won't work for icon themes, fonts, and won't respect the dark theme application preference).

Technically, I think it would be easy enough - there's already possible reference code in https://github.com/elementary/granite/pull/501 's removals, so I guess it ultimately depends on who gets to doing the pull request first, given I have a suspicion this may be the new goal instead of the current inactive pull request.

**Comment by dominichayesferen** [comment]
Nevermind, work is in progress to effectively put the stylesheet inside Granite itself(?)
https://github.com/elementary/granite/pull/639

**Comment by dominichayesferen** [comment]
I'm assuming https://github.com/elementary/granite/commit/6f035b7333ad00a972a78e6c07275a2add361565 means that once the next Granite release happens this bug can be closed as FIXED?

**Comment by dominichayesferen** [comment]
I suppose, the only thing left now is for Flatpaks to use the updated Granite.
