### ISSUE TITLE
In-app dark style setting is ignored in GNOME apps

### ISSUE THREAD

**Issue by fushinari** [elementary/flatpak-platform#73]
### What Happened?

`gtk-application-prefer-dark-theme` is ignored in GNOME apps on Flathub, even when set by the application itself.

### Steps to Reproduce

1. Install GNOME Builder from Flathub
2. Run GNOME Builder
3. Enable "Dark mode" from Preferences
4. The UI will remain light

### Expected Behavior

The UI should turn dark.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jhaygood86** [comment]
That isn't supported by elementary OS.

You can instead set the environment variable GTK_THEME toAdwaita:dark via flatpak overrides and this should work if you have the Adwaita Dark theme installed in flatpak.

**Comment by Exalm** [comment]
That's just how themes work - https://gitlab.gnome.org/GNOME/libhandy/-/merge_requests/782 includes a (very hacky) workaround for that, but it's not very reliable. libadwaita apps are guaranteed to look fine though unless you start playing with GTK_THEME etc.

**Comment by fushinari** [comment]
> That's just how themes work

I see.

>  gitlab.gnome.org/GNOME/libhandy/-/merge_requests/782 includes a (very hacky) workaround for that, but it's not very reliable. libadwaita apps are guaranteed to look fine though unless you start playing with GTK_THEME etc.

Glad to know! Thank you!
