### ISSUE TITLE
No audio feedback when taking picture with Flatpak version

### ISSUE THREAD

**Issue by jeremypw** [elementary/flatpak-platform#78]
### What Happened?

When using the Camera app, taking a picture used to be accompanied by a shutter sound.  With the Flatpak version there is no sound although the `canberra` library is still included.

### Steps to Reproduce

Run the Flatpak version of Camera
Take a photo
No sound.

### Expected Behavior

Taking a photo should give audio feedback as before.

### OS Version

6.x (Odin)

### Software Version

Compiled from git

### Log Output

```shell
On taking a photo the terminal output is:
`GLib-GObject-CRITICAL **: 18:20:17.887: g_object_get: assertion 'G_IS_OBJECT (object)' failed
`
which may or may not be relevant.  The photo is successfully taken and saved.
```

**Comment by meisenzahl** [comment]
Should be fixed by #79
